# Generated by Django 5.0.6 on 2024-08-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="delete_status",
            field=models.IntegerField(choices=[(1, "Live"), (0, "Delete")], default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (2, "ORDER_PROCESSED"),
                    (3, "ORDER_DELIVERED"),
                    (4, "ORDER_REJECTED"),
                    (1, "ORDER_CONFIRMED"),
                ],
                default=0,
            ),
        ),
    ]
