# Generated by Django 5.0.6 on 2024-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_total_price_alter_order_delete_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="delete_status",
            field=models.IntegerField(choices=[(1, "LIVE"), (0, "DELETE")], default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (2, "ORDER_PROCESSED"),
                    (3, "ORDER_DELIVERD"),
                    (4, "ORDER_REJECTED"),
                ],
                default=0,
            ),
        ),
    ]
